Bug fixes & IPv6 support
stellarbit/aioping pull request #2
Opened 2017-05-16 12:38 UTC by JackSlateur

Hi,

Please find a batch of commits I had to make

It mixes fixes (the code does not works for me as-is) and IPv6 support

Please tell me what you think, I can rebase it if you have issue with some parts or something

2017-06-20 00:54 UTC, anton-belousov requested changes
Thank you for your changes! Everything is great, but I didn't get why do we need to use synchronous submission in when sending a request.

2017-06-20 00:54 UTC, anton-belousov commented on aioping/__init__.py
> +    my_socket.sendto(packet, dest_addr)
Why do we need a synchronous submission here?

2017-08-09 16:51 UTC, JackSlateur commented
Sorry for the delay and thanks for the review

I am not sure how it should be done, there is a commit that should do better

Tell me if it's still crap :)

2017-11-09 14:33 UTC, bxwllzz requested changes

2017-11-09 14:33 UTC, bxwllzz commented on aioping/__init__.py
> +                    next
`next` is a build-in function in python. Do you mean `continue`?

2017-11-09 16:51 UTC, JackSlateur commented
Humpf shame on me, thanks for the review

2017-11-09 16:58 UTC, merged

2017-11-09 20:07 UTC, anton-belousov commented
@JackSlateur, @bxwllzz, thank you very much for contributing & checking this. Will update the library soon.